/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

//import com.mysql.cj.protocol.Resultset;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
//import com.mysql.cj.protocol.Resultset.*;
//import java.sql.prepareStatement;

/**
 *
 * @author Admin
 */



public class AddItem extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddItem
     */
    
    

    String iid;
    String iname;
    String category;
    String serialno;
    String bprice;
    String sprice;
    String noofitem;
    String barcode;
    
    Connection conn;
    
    private ImageIcon format=null;
    String fname=null;
    int s=0;
    byte[] pimage=null;
    
    
    
    
    
    
    public AddItem() {
        initComponents();
        tableLord();
//        conn = DBConnection.connect();

//        autoId();

        
       this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
       BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
       bi.setNorthPane(null);
    }

    
     public ImageIcon resizeImage(String imagePath, byte[] pic){
        
        ImageIcon myImage=null;
        if(imagePath !=null)
        {
            myImage = new ImageIcon(imagePath);
        
        }else{
            myImage=new ImageIcon(pic);
        }
        
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lblmage.getHeight(),lblmage.getWidth(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        cmbcategory = new javax.swing.JComboBox<>();
        txtiname = new javax.swing.JTextField();
        txtbprice = new javax.swing.JTextField();
        txtsprice = new javax.swing.JTextField();
        txtiid = new javax.swing.JTextField();
        txtserialno = new javax.swing.JTextField();
        txtbarcode = new javax.swing.JTextField();
        txtnoofitem = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblmage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbladditem = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(936, 530));

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(719, 524));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ADD ITEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 30));

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("Selling Price");

        label2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label2.setText("Item Id");

        label3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label3.setText("Category");

        label4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label4.setText("Item Name");

        label5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label5.setText("Serial No");

        label6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label6.setText("No of Items");

        label7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label7.setName(""); // NOI18N
        label7.setText("Buying Price");

        label8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label8.setText("BarCode");

        cmbcategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category", "Product", "Skin Care product", "Other" }));

        txtiname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtbprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtsprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspriceActionPerformed(evt);
            }
        });

        txtiid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtserialno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtbarcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtnoofitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtiname)
                                    .addComponent(cmbcategory, javax.swing.GroupLayout.Alignment.TRAILING, 0, 305, Short.MAX_VALUE)
                                    .addComponent(txtiid, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtserialno, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbarcode)
                                    .addComponent(txtnoofitem)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbprice)
                            .addComponent(txtsprice))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtiname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtserialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtbprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtsprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnoofitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 310));

        lblmage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delete");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Brows");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel6)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clear");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmage, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 470, 310));

        tbladditem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbladditem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladditemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbladditem);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 910, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtspriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspriceActionPerformed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
      
         //txtiid.setText("");
       //txtiname.setText("");
        //cmbcategory.setText("");
       // txtserialno.setText("");
        //txtbprice.setText("");
        //txtsprice.setText("");
       // txtnoofitem.setText("");
         //txtbarcode.setText("");
         //JOptionPane.showMessageDialog(null, "field clear");
        
        
        
        
      JFileChooser fchoser=new JFileChooser();
       fchoser.showOpenDialog(null);
       File f=fchoser.getSelectedFile();
       fname=f.getAbsolutePath();
       ImageIcon micon=new ImageIcon(fname);
       try{
           File image=new File(fname);
           FileInputStream fis=new FileInputStream(image);
           ByteArrayOutputStream baos=new ByteArrayOutputStream();
           byte[] buf=new byte[1024];
           for(int readnum; (readnum=fis.read(buf)) !=-1;)
           {
               baos.write(buf,0,readnum);
           }
           pimage=baos.toByteArray();
           lblmage.setIcon(resizeImage(fname,buf));
       }catch (Exception e){
         JOptionPane.showMessageDialog(null, "Browse product photo");  
       }
        
        
        
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        
        getdata();
       try{
           //Class.forName("Com.mysql.cj.jdbc.Driver");
           //conn=DriverManager.getConnection("jdbc:mysql://localhost:3307/newinventory","root","");
            int barco = Integer.parseInt(txtbarcode.getText());
            //String q= "INSERT INTO `stock`(`item_name`, `category`, `serial_no`, `buy_price`, `sale_price`, `no_of_items`, `barcode`,`mark`) VALUES (?,?,?,?,?,?,?,?)";
            String q= "INSERT INTO `stock`( `item_name`, `category`, `serial_no`, `buy_price`, `sale_price`, `no_of_items`, `barcode`, `mark`) VALUES (?,?,?,?,?,?,?,?)";
            //pst= (PreparedStatement) conn.preparedStatement(q);
//             pst= (PreparedStatement) DBConnection.connect().PrepareStatement(q);
             PreparedStatement pst =  DBConnection.connect().prepareStatement(q);
             
//              pst.setString(1,iid);
              pst.setString(1,iname);
              pst.setString(2,category);
              pst.setString(3,serialno);
              pst.setString(4,bprice);
              pst.setString(5,sprice);
              pst.setString(6,noofitem);
              //pst.setBytes(7,pimage);
              pst.setInt(7,barco);
              pst.setString(8, "1");
              pst.executeUpdate();
              
              clearData();
              tableLord();
              JOptionPane.showMessageDialog(null, "item Added");
        }catch (Exception e){
            System.out.println("Item Added : "+e);
        }
          
        
        
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
       
        getdata();
        try{
            int barco = Integer.parseInt(txtbarcode.getText());
           // String squpdate = "UPDATE `stock` SET `item_name`=?,`category`=?,`serial_no`=?,`buy_price`=?,`sale_price`=?,`no_of_items`=?,`barcode`=?,`mark`=? WHERE item_id=?";
//               String squpdate ="UPDATE `stock` SET `item_name`=?,`category`=?,`serial_no`=?,`buy_price`=?,`sale_price`=?,`no_of_items`=?,`barcode`=?,`mark`=? WHERE item_id=?";  
               String squpdate ="UPDATE `stock` SET `item_name`=?,`category`=?,`serial_no`=?,`buy_price`=?,`sale_price`=?,`no_of_items`=?,`barcode`=?,`mark`=? WHERE item_id = ?";  
               
             PreparedStatement pst =  DBConnection.connect().prepareStatement(squpdate);
             
              pst.setString(1,iname);
              pst.setString(2,category);
              pst.setString(3,serialno);
              pst.setString(4,bprice);
              pst.setString(5,sprice);
              pst.setString(6,noofitem);
              pst.setString(7,txtbarcode.getText());
              pst.setString(8, "1");
              pst.setInt(9,Integer.parseInt(txtiid.getText()));
              pst.executeUpdate();
          if(pst.executeUpdate()==1){    
               getdata();
               tableLord();
          JOptionPane.showMessageDialog(null, "Item Update");
         
          }else{
              JOptionPane.showMessageDialog(this, "Missing Information");
          }
        }catch(Exception e){
            System.out.println("Item updated : "+e);
        }
        clearData();
       
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
         try{
            
            String sql="DELETE FROM `stock` WHERE item_id='"+ txtiid.getText() +"'";
            PreparedStatement pst =  DBConnection.connect().prepareStatement(sql);
            pst.executeUpdate();
            tableLord();
            JOptionPane.showMessageDialog(null, "item deleted");
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        

        String name = txtiname.getText();
        System.out.println(name);
        try {
            
//            String search = "Select * from stock where item_name like %"+name+"%";
            String search = "SELECT * FROM stock WHERE item_name LIKE '%"+name+"%'";
//             PreparedStatement pst =  DBConnection.connect().prepareStatement(search);
            Statement stmt = DBConnection.connect().createStatement();
//             ResultSet rs = pst.executeQuery();
             ResultSet rs = stmt.executeQuery(search);
             
             while(rs.next()){

                   txtiid.setText(String.valueOf(rs.getInt(1)));
                   txtserialno.setText(rs.getString(4));
                   txtbprice.setText(rs.getString(5));
                   txtsprice.setText(rs.getString(6));
                   txtnoofitem.setText(rs.getString(7));
                   txtbarcode.setText(rs.getString(8));
                   JOptionPane.showMessageDialog(null, "item selected");
             }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void tbladditemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladditemMouseClicked
//       tableLord();



//        //String id;
//        //DefaultTableModel tmodel=(DefaultTableModel)tbladditem.getModel();
//       // int selectrowindex=tbladditem.getSelectedRow();
//        //id = (tmodel.getValueAt(selectrowindex, 0).toString());
//        
        //try{
          // String sql="SELECT `item_id`, `item_name`, `category`, `serial_no`, `buy_price`, `sale_price`, `no_of_items`, `image`, `barcode`, `mark` FROM `stock` WHERE item_id='"+id+"'";
           //PreparedStatement pst =  DBConnection.connect().prepareStatement(sql);
          // Resultset rs=(Resultset) pst.executeQuery();
          //if(rs.next())
          //{
             // txtid.setText(rs.getString("item_id"));
              //txtiname.setText(rs.getString("item_name"));
              //cmbcategory.setSelectedItem(rs.getString("category"));
              //txtserialno.setText(rs.getString("serial_no"));
              //txtbprice.setText(rs.getString("buy_price"));
              //txtsprice.setText(rs.getString("sale_price"));
              //txtnoofitem.setText(rs.getString("no_of_items"));
              
             //byte[] imagedata=rs.getBytes("image");
             //format=new ImageIcon(imagedata);
             //Image mm=format.getImage();
            // Image img2=mm.getScaledInstance(lblmage.getWidth(), lblmage.getHeight(), Image.SCALE_SMOOTH);
            // ImageIcon image=new ImageIcon(img2);
             //lblmage.setIcon(image);
              
          //}
            
       // }catch(Exception e){
         // JOptionPane.showMessageDialog(rootPane, e);  
        //}
        
        
   /// }   
   DefaultTableModel dmodel=(DefaultTableModel)tbladditem.getModel();
    int selectrowindex=tbladditem.getSelectedRow();
//    id = (dmodel.getValueAt(selectrowindex, 0).toString());
    int myindex=tbladditem.getSelectedRow();
    txtiid.setText(dmodel.getValueAt(myindex, 0).toString());
    txtiname.setText(dmodel.getValueAt(myindex, 1).toString());
    cmbcategory.setSelectedItem(dmodel.getValueAt(myindex, 2).toString());
    txtbprice.setText(dmodel.getValueAt(myindex, 3).toString());
    txtserialno.setText(dmodel.getValueAt(myindex, 4).toString());
    txtsprice.setText(dmodel.getValueAt(myindex, 5).toString());
    txtnoofitem.setText(dmodel.getValueAt(myindex, 6).toString());
   // lblmage.setIcon(frameIcon);
    txtbarcode.setText(dmodel.getValueAt(myindex, 7).toString());
    
    //lblmage.setIcon(frameIcon);
    
//     byte[] imagedata;
//        imagedata = dmodel.getBytes(pimage);
//     format=new ImageIcon(imagedata);
//     Image mm=format.getImage();
//     Image img2=mm.getScaledInstance(lblmage.getWidth(),        lblmage.getHeight(), Image.SCALE_SMOOTH);
//     ImageIcon image=new ImageIcon(img2);
//     lblmage.setIcon(image);
     
//             Image img=lblmage.getIcon(pimage);
//        Image img2=img.getScaledInstance(lblmage.getHeight(),lblmage.getWidth(), Image.SCALE_SMOOTH);
//        ImageIcon images=new ImageIcon(img2);
    
//    lblmage.setText(dmodel.getValueAt(myindex, 6).toString());
//        byte[] imagedata=rs.getBytes("image");
//        Image mm=format.getImage();
//        Image img2=mm.getScaledInstance(lblmage.getWidth(), lblmage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image=new ImageIcon(img2);
//        lblmage.setIcon(image);
    }//GEN-LAST:event_tbladditemMouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        
        txtiid.setText("");
       txtiname.setText("");
        //cmbcategory.setText("");
       txtserialno.setText("");
        txtbprice.setText("");
        txtsprice.setText("");
        txtnoofitem.setText("");
        txtbarcode.setText("");
         JOptionPane.showMessageDialog(null, "field clear");
        
    }//GEN-LAST:event_jPanel10MouseClicked

    private void tableLord()
   {
       
       try{
           
           String sql="SELECT `item_id`, `item_name`, `category`, `serial_no`, `buy_price`, `sale_price`, `no_of_items`,  `barcode`, `mark` FROM `stock`";
           PreparedStatement pst =  DBConnection.connect().prepareStatement(sql);
           ResultSet rs=(ResultSet) pst.executeQuery();
           tbladditem.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel((java.sql.ResultSet) rs));
           
       }catch(Exception e){
           
       }
       
   }
    
    
    
    
     private void clearData()
    {
       //autoId();
        txtiname.setText("");
        cmbcategory.setSelectedIndex(0);
        txtserialno.setText("");
        txtbprice.setText("");
        txtsprice.setText("");
        txtnoofitem.setText("");
        
    }
    
    
    
    
    
     private void getdata()
    {
       iid = txtiid.getText();
       iname = txtiname.getText();
       category = cmbcategory.getSelectedItem().toString();
       serialno = txtserialno.getText();
       bprice = txtbprice.getText();
       sprice = txtsprice.getText();
       noofitem = txtnoofitem.getText();
    }
    
     private void autoId()
    {
        try{
            String sql= "SELECT item_id FROM stock ORDER BY item_id DESC LIMIT 1";
//            pst=(PreparedStatement) conn.PrepareStatement(sql);
             PreparedStatement pst =  DBConnection.connect().prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
           if(rs.next())
           {
                String rnno=rs.getString("item_id");
                int co=rnno.length();
                String txt= rnno.substring(0,2);
                String num=rnno.substring(2,co);
                int n=Integer.parseInt(num);
                n++;
                String snum=Integer.toString(n);
                String ftxt=txt+snum;
                txtiid.setText(ftxt);  
           }
            else
           {
              txtiid.setText("IID1000");
            //txtid.setText("IID1000");
           }
    }catch (Exception e){
         JOptionPane.showMessageDialog(rootPane, e);
    }
}
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JLabel lblmage;
    private javax.swing.JTable tbladditem;
    private javax.swing.JTextField txtbarcode;
    private javax.swing.JTextField txtbprice;
    private javax.swing.JTextField txtiid;
    private javax.swing.JTextField txtiname;
    private javax.swing.JTextField txtnoofitem;
    private javax.swing.JTextField txtserialno;
    private javax.swing.JTextField txtsprice;
    // End of variables declaration//GEN-END:variables

   // private static class prepareStatement {

       // public prepareStatement() {
        //}
   // }
}
